version: "3.8"
services:
  jelly-request:
    build: .
    container_name: jelly-request
    environment:
      - JELLYSEERR_URL=http://192.168.0.29:5055
      - JELLYSEERR_EMAIL=youruser@example.com
      - JELLYSEERR_PASSWORD=yourpassword
      - IS_4K_REQUEST=true
      - RUN_INTERVAL_DAYS=7
      - MOVIE_LIMIT=30
      - DEBUG_MODE=SIMPLE
    volumes:
      - ./logs:/logs
